#!/bin/bash

# This file is part of Kaya.
#
# Kaya is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Kaya is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Kaya.  If not, see <https://www.gnu.org/licenses/>.
#
# Copyright 2021 Andrew Engelbrecht
#

if ! test "$BASH_VERSION"; then echo "error: shell is not bash" >&2; exit 1; fi
shopt -s inherit_errexit 2>/dev/null ||: # ignore fail in bash < 4.4
set -eE -o pipefail
trap 'echo "$0:$LINENO:error: \"$BASH_COMMAND\" exit status: $?, PIPESTATUS: ${PIPESTATUS[*]}" >&2' ERR

read -r password

port="$1"
hostname="$2"
shift 2

username="${hostname}"
backupdir="${hostname}"

export RESTIC_REPOSITORY="rest:http://${username}:${password}@localhost:${port}/${backupdir}/"
export RESTIC_PASSWORD="${password}"

cmd=( restic backup "$@")
ret=0
"${cmd[@]}" || ret=$?

if (( ret )); then
    echo "kaya-client: command exit code $ret: ${cmd[*]}"
    exit $ret
fi
